Repository LimeChain/hedera-mirror-node, pull requests merged in 2020-08, with the labels that each got.

#51 feature(hedera-mirror-rosetta): add barebone structure
  hedera-mirror-rosetta/.env.example
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/main.go
Labels: enhancement

#52 Feature(hedera-mirror-rosetta): Docker configuration
  docker-compose.yml
  hedera-mirror-rosetta/.env.example
  hedera-mirror-rosetta/Dockerfile
Labels: enhancement

#53 Feature/hedera mirror rosetta/db connection
  docker-compose.yml
  hedera-mirror-rosetta/.env.example
  hedera-mirror-rosetta/Dockerfile
  hedera-mirror-rosetta/cmd/db.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/main.go
  hedera-mirror-rosetta/services/block_service.go
Labels: enhancement

#55 Add Block Repository functions
  hedera-mirror-rosetta/app/domain/repositories/block.go
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/cmd/main.go
Labels: enhancement

#57 Remove Duplicated Services folder
  hedera-mirror-rosetta/services/block_service.go
Labels: bug

#58 Feature/get transactions
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
Labels: enhancement

#59 Feature: /network/list
  docs/configuration.md
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-rosetta/types/config.go
Labels: enhancement

#60 Rosetta API Description
  docs/images/rosetta-server.png
  docs/rosetta-server.md
Labels: documentation

#61 Feature/construct block response
  hedera-mirror-rosetta/app/domain/repositories/block.go
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
Labels: enhancement

#63 Feature/change block index to consensus start
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
Labels: bug

#64 Feature(hedera-mirror-rosetta): Error handling
  hedera-mirror-rosetta/app/domain/repositories/block.go
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
Labels: enhancement

#67 Full implementation of block API call
  hedera-mirror-rosetta/app/domain/services/entity-id-codec.go
  hedera-mirror-rosetta/app/domain/services/entity-id-codec_test.go
  hedera-mirror-rosetta/app/domain/types/account.go
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
Labels: bug, enhancement

#68 Feature/block transaction request
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/types/account.go
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/tools/hex/hex.go
Labels: bug, enhancement

#69 (After #68) Feature/mempool and /mempool/transaction
  hedera-mirror-rosetta/app/domain/services/entity_id_codec.go
  hedera-mirror-rosetta/app/domain/services/entity_id_codec_test.go
  hedera-mirror-rosetta/app/services/mempool_service.go
  hedera-mirror-rosetta/cmd/main.go
Labels: enhancement

#71 Feat(hedera-mirror-rosetta): ConstructionAPI /payloads, /metadata, /derive and /preprocess
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/cmd/config.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/config.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/tools/validator/validator.go
Labels: enhancement

#73 Feature/account balance
  hedera-mirror-rosetta/app/domain/repositories/account.go
  hedera-mirror-rosetta/app/domain/types/amount.go
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/account/account.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/persistance/postgres/types/common.go
  hedera-mirror-rosetta/app/services/account_service.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/app/services/commons.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/cmd/main.go
Labels: enhancement

#72 Feature(hedera-mirror-rosetta): Construction API - '/combine', '/hash' and '/submit'
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
Labels: enhancement

#76 Refactor/transaction identifier
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/services/entity-id-codec/entity_id_codec.go
  hedera-mirror-rosetta/app/domain/services/entity-id-codec/entity_id_codec_test.go
  hedera-mirror-rosetta/app/domain/types/account.go
  hedera-mirror-rosetta/app/domain/types/transaction.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/block_service.go
Labels: bug

#77 Fix(hedera-mirror-rosetta): Construction API '/payloads' -> return tx body as payload to be signed
  hedera-mirror-rosetta/app/services/construction_service.go
Labels: bug

#78 Bugs/cli validation 1
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/services/account_service.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/app/services/network_service.go
Labels: bug

#79 Refactor the Block Index
  hedera-mirror-rosetta/app/domain/types/block.go
  hedera-mirror-rosetta/app/persistance/postgres/block/block.go
  hedera-mirror-rosetta/app/services/network_service.go
Labels: bug

#82 Bugs/cli validation 3
  hedera-mirror-rosetta/app/persistance/postgres/account/account.go
  hedera-mirror-rosetta/app/services/account_service.go
Labels: bug

#84 Feature(hedera-mirror-rosetta): Return Peers & Update Hash
  hedera-mirror-rosetta/app/domain/repositories/addressbook/entry/entry.go
  hedera-mirror-rosetta/app/domain/types/address_book_entry.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistance/postgres/addressbook/entry/entry.go
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/cmd/main.go
Labels: enhancement

#85 Infra/add rosetta validation
  .github/workflows/rosetta-validation.yml
  .github/workflows/wait-for-mirror-node.sh
  hedera-mirror-rosetta/app/persistance/postgres/transaction/transaction.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/run-validation.sh
  hedera-mirror-rosetta/validation/demo_data_genesis_balances.json
  hedera-mirror-rosetta/validation/validate-from-block-10.json
  hedera-mirror-rosetta/validation/validate-from-genesis.json
Labels: enhancement

#89 Feature(hedera-mirror-rosetta): Rosetta validation config for testnet
  hedera-mirror-rosetta/run-validation.sh
  hedera-mirror-rosetta/validation/demo/data_genesis_balances.json
  hedera-mirror-rosetta/validation/demo/validate-from-block-10.json
  hedera-mirror-rosetta/validation/demo/validate-from-genesis.json
  hedera-mirror-rosetta/validation/testnet/data_genesis_balances.json
  hedera-mirror-rosetta/validation/testnet/validate-from-genesis.json
  hedera-mirror-rosetta/validation/validate-from-genesis.json
Labels: enhancement

#91 Ci(hedera-mirror-rosetta): Switch Rosetta validation trigger
  .github/workflows/rosetta-validation.yml
Labels: enhancement

#94 Feature(hedera-mirror-rosetta): Remove CryptoCreateAccount handle
  docs/configuration.md
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-rosetta/config/config.go
  hedera-mirror-rosetta/tools/validator/validator.go
Labels: enhancement

#101 Feature(hedera-mirror-rosetta): run in online/offline mode + read .env
  docs/configuration.md
  hedera-mirror-rosetta/cmd/config.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-rosetta/config/config.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/types/config.go
Labels: enhancement
